name: Run Linting

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Run make setup
      run: make setup
    - name: Run mypy
      run: make mypy
      if: ${{ always() }}
    - name: Pylint
      id: pylint
      run: make pylint-ci
      if: ${{ always() }}
    - name: Blacken
      run: make blacken-ci
      if: ${{ always() }}
    - name: Flake8
      run: make flake8-ci
      if: ${{ always() }}
